#!/usr/bin/env bash

scripts_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter="$1"

dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

log "$scripts_dir -- $filter"
cd $scripts_dir
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -type f -perm +ugo+x)

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtering $script"
    continue
  fi
  execute ./$script
done
