- name: Symlink yabai config
  ansible.builtin.file:
    src: "{{ config_directory }}.yabairc"
    dest: '{{ ansible_env.HOME }}/.yabairc'
    state: link
    force: yes
    mode: u+x
  tags:
  - window-manager
- name: Copy skhd config
  ansible.builtin.file:
    src: "{{ config_directory }}.skhdrc"
    dest: '{{ ansible_env.HOME }}/.skhdrc'
    state: link
    force: yes
    mode: u+x
  tags:
  - window-manager
- name: Start yabai process
  ansible.builtin.shell: brew services start yabai
  tags:
  - window-manager
- name: Start skhd process
  ansible.builtin.shell: brew services start skhd
  tags:
  - window-manager